when:
  - event: push
    branch: main

steps:
  - name: build
    image: python:3.12-bookworm
    commands:
      - echo "Start Pipeline"
      - python3 -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python3 -m pip install --upgrade pip
      - python3 -m pip install sphinx sphinx-rtd-theme myst-parser
      - python3 generate_index.py
      - ls
      - sphinx-build . _build/
  - name: publish
    image: bitnami/git
    environment:
      # secrets must be set in Woodpecker configuration
      secrets: [mail, cbtoken]
    commands:
      # config git to commit and push changes
      - git config --global --add safe.directory $CI_WORKSPACE/public
      - echo safe dir set successfully
      - git config --global user.email $MAIL
      - echo mail set successfully
      - git config --global user.name "Woodpecker CI"
      - echo user name set successfully
      - git config --global init.defaultBranch pages
      - echo default branch set successfully
      # clone the existing pages branch which will be updated with new doc build
      - git clone -b pages https://$CBTOKEN@codeberg.org/derreparierer/derreparierer2.git build_docs
      - echo git clone branch was successful
      # purge existing docs
      - rm -rf build_docs/*
      - echo purge existing docs was successful
      # add new docs
      - cp -a _build/* build_docs/
      - echo add new docs was successful
      # commit and push to pages branch
      - cd build_docs/
      - echo cd build_docs/ was successful
      - git remote set-url origin https://$CBTOKEN@codeberg.org/derreparierer/derreparierer2.git
      - echo set remote-url was successful
      - git add --all
      - echo git add was successful
      # exclude current push from CI pipeline triggering
      - git commit -m "deploy $CI_COMMIT_SHA [CI SKIP]"
      - echo git commit was successful
      - git push -u origin pages
      - echo git push to pages was successful
